Erster Stand für pr
Pierre414/E2E pull request #1
Opened 2021-03-29 07:33 UTC by Pierre414

2021-03-29 08:03 UTC, PB1994 requested changes

2021-03-29 08:03 UTC, PB1994 commented on Money.test.ts
> +});
Leerzeile

2021-03-29 08:03 UTC, PB1994 commented on Money.test.ts
> +    expect(functions.testmultiplication()).toBe(10)
```suggestion
    const fiveDollars = new Doller(5);
    fiveDollars.times(2);
    expect(fiveDollars).toBe.Equal(new Doller(10));
```

2021-03-29 08:03 UTC, PB1994 commented on Money.test.ts
> +test('testmultiplication equal 10',()=>{
```suggestion
test('5 Dollars time 2 is 10',()=>{
```

2021-03-29 08:03 UTC, PB1994 commented on Money.ts
> +class Dollar {
```suggestion
export class Dollar {
```

2021-03-29 08:03 UTC, PB1994 commented on Money.ts
> +    times(multiplier): void {
```suggestion
    times(multiplier: number): void {
```

2021-03-29 08:03 UTC, PB1994 commented on Money.ts
> +    amount: number;
```suggestion
    public amount: number;
```

2021-03-29 08:03 UTC, PB1994 commented on Money.ts
> +    times(multiplier): void {
```suggestion
    public times(multiplier): void {
```

2021-03-29 08:03 UTC, PB1994 commented on Money.ts
> +    five: Dollar = new Dollar(5);
```suggestion
```

2021-03-29 08:03 UTC, PB1994 commented on Money.ts
> +    }
```suggestion
    public equals(obj: Dollar) : boolean { 
         return this.amount == obj.amount;
    } 
```

2021-03-29 08:03 UTC, PB1994 commented on Money.ts
> +module.exports = functions;
```suggestion
```

2021-03-31 11:31 UTC, PB1994 requested changes

2021-03-31 11:31 UTC, PB1994 commented on .gitignore
> +node_modules
package-lock und yarn.lock noch mit rein und die Dateien dann nicht mit comitten

2021-03-31 11:31 UTC, PB1994 commented on Money.test.ts
> +    fiveDollars.dollartimes(2)
```suggestion
    const tenDollars = fiveDollars.dollartimes(2);
```

2021-03-31 11:31 UTC, PB1994 commented on Money.test.ts
> +    const fiveDollars = Money.dollar(5,null);
```suggestion
    const fiveDollars = Money.dollar(5,'Dollar');
```

2021-03-31 11:31 UTC, PB1994 commented on Money.test.ts
> +    fiveFranc.franctimes(3)
```suggestion
    fiveFranc.franctimes(3);
```

2021-03-31 11:31 UTC, PB1994 commented on Money.test.ts
> +    fiveDollars.dollartimes(3)
```suggestion
    fiveDollars.dollartimes(3);
```

2021-03-31 11:31 UTC, PB1994 commented on Money.test.ts
> +    expect(Money.dollar(5,'Dollar')).toStrictEqual(Money.dollar(5,'Dollar'))
```suggestion
    expect(Money.dollar(5,'Dollar')).toStrictEqual(Money.dollar(5,'Dollar'));
```

2021-03-31 11:31 UTC, PB1994 commented on Money.test.ts
> +    let sum:Money=Money.dollar(5,null).plus(Money.dollar(5,null));
```suggestion
   const fiveDollars = Money.dollar(5,'Dollar');
   const threeDollars = Money.dollar(3,'Dollar');
```

2021-03-31 11:31 UTC, PB1994 commented on Money.test.ts
> +    expect(sum.getamount()).toBe(sum2.getamount());
```suggestion
    expect(fiveDollars.plus(threeDollars).getamount()).toBe(8);
```

2021-03-31 11:31 UTC, PB1994 commented on Money.test.ts
> +
describe('The Money object) => {tests...};

2021-03-31 11:31 UTC, PB1994 commented on Money.test.ts
> +test('simple Addition',()=>{
```suggestion
test('adds another Money object',()=>{
```

2021-03-31 11:31 UTC, PB1994 commented on Money.ts
> +    return this.amount;
```suggestion
    return Money.dollar(this.amount, this.currency);
```

2021-03-31 11:31 UTC, PB1994 commented on Money.ts
> +    return this.currency
s.o.

2021-03-31 11:31 UTC, PB1994 commented on Money.ts
> +  public getamount(): number {
```suggestion
  public getAmount(): number {
```

2021-03-31 11:31 UTC, PB1994 commented on Money.ts
> +  }
```suggestion
  static dollar(amount: number, ): Money {
    return new Money(amount, 'USB');
  }
```

2021-04-06 09:16 UTC, PB1994 requested changes

2021-04-06 09:16 UTC, PB1994 commented on .gitignore
> +jest.config.js
yarn.lock

2021-04-06 09:16 UTC, PB1994 commented on Money.test.ts
> +// });
```suggestion
```

2021-04-06 09:16 UTC, PB1994 commented on Money.ts
> +// import { Franc } from "./Franc";
```suggestion
```

2021-04-06 09:16 UTC, PB1994 commented on Money.test.ts
> +// })
```suggestion
```

2021-04-06 09:16 UTC, PB1994 commented on Money.ts
> +      return Money.dollar(this.amount,'CHF');
```suggestion
      return Money.franc(this.amount,'CHF');
```

2021-04-06 09:16 UTC, PB1994 commented on Sum.ts
> +}
Leerzeile ans Ende

2021-04-06 09:16 UTC, PB1994 commented on Money.test.ts
> +    expect(Money.dollar(10)).toBe(result);
```suggestion
    expect(Money.dollar(7)).toBe(result);
```

2021-04-06 09:16 UTC, PB1994 commented on Money.test.ts
> +// import { Franc } from "./Franc"
```suggestion
```

2021-04-06 13:01 UTC, quitejonny requested changes

2021-04-06 13:01 UTC, quitejonny commented on Money.test.ts
> +    expect(Money.dollar(5)).toStrictEqual(Money.dollar(5));
Warum nicht die eigene Implementierung verwenden?

2021-04-06 13:01 UTC, quitejonny commented on Money.ts
> +  }
```suggestion
```

2021-04-06 13:01 UTC, quitejonny commented on Money.test.ts
> +
```
test('5 Franc times 6  in Dollar', () => {
    const franc = Money.franc(5);
    const result = franc.dollarTimes(6);
});
```
-> Testen, dass das obere Beispiel nicht funktioniert

2021-04-06 13:01 UTC, quitejonny commented on Money.test.ts
> +    const tenFranc=fiveFranc.francTimes(3);
```suggestion
    const tenFranc=fiveFranc.times(3);
```

2021-04-06 13:01 UTC, quitejonny commented on Money.ts
> +    return Money.dollar(this.amount, "USD");
```suggestion
    return new Money(amount, this.currency);
```

2021-04-06 13:01 UTC, quitejonny commented on Money.test.ts
> +    expect(tenDollars.getAmount()).toBe(10);
```suggestion
    expect(tenDollars.getAmount()).toBe(10);
    expect(fiveDollars.getAmount()).toEqual(5);
```

2021-04-06 13:01 UTC, quitejonny commented on Money.ts
> +    this.amount = this.amount * multiplier;
```suggestion
    const amount = this.amount * multiplier;
```

2021-04-07 09:11 UTC, quitejonny requested changes

2021-04-07 09:11 UTC, quitejonny commented on Money.test.ts
> +});
noch Test schreiben um zu prüfen, dass nach `times` fiveFranc immer noch fiveFranc sind

2021-04-07 09:11 UTC, quitejonny commented on Money.ts
> +  private currency: String;
```suggestion
  private readonly amount: number;
  private readonly currency: String;
```

2021-04-07 12:55 UTC, PB1994 requested changes

2021-04-07 12:55 UTC, PB1994 commented on Money.test.ts
> +    let five:Money=Money.dollar(5);
```suggestion
    const fiveDollar =Money.dollar(5);
```

2021-04-08 09:25 UTC, PB1994 requested changes

2021-04-08 09:25 UTC, PB1994 commented on Money.test.ts
> +    const tenFranc = fiveFranc.times(3);
```suggestion
    fiveFranc.times(3);
```

2021-04-08 09:25 UTC, PB1994 commented on Money.test.ts
> +    let result=five.plus(five);
```suggestion
    const sum = five.plus(five);
```

2021-04-08 09:25 UTC, PB1994 commented on Money.test.ts
> +    let sum:Sum=result;
```suggestion
```

2021-04-08 09:25 UTC, PB1994 commented on Money.test.ts
> +    let bank=new Bank();
```suggestion
    const bank = new Bank();
```

2021-04-08 09:25 UTC, PB1994 commented on Money.test.ts
> +    const sum:Expression=new Sum(Money.dollar(3),Money.dollar(4))
```suggestion
    const sum = Money.dollar(3).plus(Money.dollar(4));
```

2021-04-08 09:25 UTC, PB1994 commented on Money.test.ts
> +    const result:Money=bank.reduce(sum,'USD');
```suggestion
    const addResult:Money=bank.reduce(sum,'USD');
```

2021-04-08 09:25 UTC, PB1994 commented on Bank.ts
> +    private rates:Hashtable=new Hashtable();
```suggestion

    reduce(source:Expression,to:String){
      return source.reduce(this,to);
    }
   
    rate(from:String,to:String):number{
        return from === "CHF" && to ===  "USD"  ? 2 : 1;
    }
    
    private rates:Hashtable=new Hashtable();
```

2021-04-08 09:25 UTC, PB1994 commented on Money.ts
> +
```suggestion
```

2021-04-08 09:25 UTC, PB1994 commented on Money.ts
> +}
```suggestion
}

```

2021-04-08 09:25 UTC, PB1994 commented on Money.ts
> +  plus(addend: Money): Expression {
```suggestion
  public plus(addend: Money): Expression {
```

2021-04-08 09:25 UTC, PB1994 commented on Money.ts
> +    :1;
```suggestion
    const rate:number=(this.currency.equals("CHF") && to.equals("USD")) ? 2 : 1;
```

2021-04-08 09:25 UTC, PB1994 commented on Pair.ts
> +}
```suggestion
}

```

2021-04-08 09:25 UTC, PB1994 commented on Sum.ts
> +        let amount:number=this.augend.getAmount()+this.addend.getAmount();
```suggestion
        const amount:number = this.augend.getAmount() + this.addend.getAmount();
```

2021-04-08 10:30 UTC, merged